name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello, World!"
      
      - name: Display Run ID
        run: echo "Run ID ${{ github.run_id }}"

      - uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: some_other_identifier
          title: Some Title
          blueprint: hello_world
          properties: |-
            {
              "name": "string"
            }
